version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Datathon-rimac
    working_dir: /app
    command: tail -F anything
    volumes:
      - .:/app
    ports:
      - "7860:7860"