cities = {
    "Lima": 'LIM',
    "Tacna": 'TAC',
    "Tumbes": 'TUM',
    "Arequipa": 'ARE',
    "Cusco": 'CUS',
    "La Libertad": 'LAL',
    "Piura": 'PIU',
    "Ica": 'ICA',
    "Puno": 'PUN',
    "Ayacucho": 'AYA',
    "Cajamarca": 'CAJ',
    "Amazonas": 'AMA',
    "Áncash": 'ANC',
    "Apurímac": 'APU',
    "Arequipa": 'ARE',
    "Ayacucho": 'AYA',
    "Cajamarca": 'CAJ',
    "Huanuco": 'HUC',
    "Huancavelica": 'HUV',
    "Junín": 'JUN',
    "Lambayeque": 'LAM',
    "Loreto": 'LOR',
    "Madre de Dios": 'MDD',
    "Moquegua": 'MOQ',
    "Pasco": 'PAS',
    "San Martín": 'SAM',
    "Ucayali": 'UCA',
}